---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: mysql
  name: mysql-placement-2
  namespace: mysql
spec:
  clusterSelector:
    matchLabels:
      'managed-cluster': 'true'
---
