apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
  namespace: mysql
spec:
  host: todo.apps.ocp4-mng.example.com/todo
    #path: "/test"
  to:
    kind: Service
    name: frontend
