apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: mysql
spec:
  host: todo.apps.ocp4.example.com/todo
  to:
    kind: Service
    name: frontend
    weight: 100
  wildcardPolicy: None

